name: frontend
description: Frontend for DBMS project
publish_to: 'none'
version: 1.0.0
repository: https://github.com/Risav25Pokhrel/dbms_frontend

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^5.1.0
  auto_size_text: ^3.0.0
  intl: ^0.18.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
