name: frontend
description: Frontend for DBMS project
version: 1.0.0
repository: https://github.com/risav25pokhrel/dbms_frontend

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^5.1.0
  http: ^1.1.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
